import "@/styles/globals.css";
import type { AppProps } from "next/app";
import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { TmaSDKLoader } from "@/components/TmaSDKLoader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <TmaSDKLoader>
        <Component {...pageProps} />
      </TmaSDKLoader>
    </>
  );
}
